uploads = []
outputs = []

[[generated]]
id = "dVrOrXhe7igq0bH2daewO"
uri = "file://artifacts/mockup-sandbox/public/images/ankara.png"
type = "image"
title = "generated_image"

[[generated]]
id = "d-_KPSB8pbtc1tGMdEfWS"
uri = "file://artifacts/mockup-sandbox/public/images/istanbul.png"
type = "image"
title = "generated_image"

[[generated]]
id = "gKY3QXERkNlgpf1rbJYcC"
uri = "file://artifacts/mockup-sandbox/public/images/izmir.png"
type = "image"
title = "generated_image"

[[generated]]
id = "TNMO7QMNl5cb3BjvfBTWs"
uri = "file://artifacts/mockup-sandbox/public/images/samsun.png"
type = "image"
title = "generated_image"

[[generated]]
id = "22qEXHq98g8NF656Jthq9"
uri = "file://artifacts/mockup-sandbox/public/images/eskisehir.png"
type = "image"
title = "generated_image"

[[generated]]
id = "gH0FWVsUBklMn3SXOkjKB"
uri = "file://artifacts/mockup-sandbox/public/images/antalya.png"
type = "image"
title = "generated_image"
