kind = "mobile"
previewPath = "/"
title = "GezIN"
version = "1.0.0"
id = "artifacts/gezin"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/" ]
localPort = 24238

[services.development]
run = "pnpm --filter @workspace/gezin run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/gezin", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/gezin", "run", "serve" ]

[services.env]
PORT = "24238"
BASE_PATH = "/"
